# ------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright © 2024 bomctl a Series of LF Projects, LLC
# SPDX-FileName: .golangci.yml
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
---
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

run:
  concurrency: 6
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - forcetypeassert
        - funlen
        - gochecknoglobals
        - goconst
        - gocyclo

  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0

  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0

  new-from-rev: ""

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - err113
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - revive
    - staticcheck
    - stylecheck
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  exhaustive:
    # https://golangci-lint.run/usage/linters/#exhaustive
    default-signifies-exhaustive: true

  funlen:
    ignore-comments: true

  govet:
    enable:
      - fieldalignment

  godox:
    keywords:
      - BUG
      - FIXME
      - HACK

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/bomctl/bomctl)

  gocritic:
    enabled-checks:
      # Diagnostic
      - commentedOutCode
      - nilValReturn
      - sloppyReassign
      - weakCond
      - octalLiteral

      # Performance
      - appendCombine
      - equalFold
      - hugeParam
      - indexAlloc
      - rangeExprCopy
      - rangeValCopy

      # Style
      - boolExprSimplify
      - commentedOutImport
      - docStub
      - emptyFallthrough
      - emptyStringTest
      - hexLiteral
      - methodExprCall
      - stringXbytes
      - typeAssertChain
      - unlabelStmt
      - yodaStyleExpr

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnamedResult
      - unnecessaryBlock

  nolintlint:
    allow-unused: false
    require-specific: true

  revive:
    enable-all-rules: true

    rules:
      - name: add-constant
        exclude: [TEST]
        arguments:
          - maxLitCount: "5"
            allowStrs: '""'
            allowInts: 0,1,2
            allowFloats: 0.0,0.,1.0,1.,2.0,2.
            ignoreFuncs: os\.*,fmt\.*,make,viper\.*

      - name: cognitive-complexity
        exclude: [TEST, ~cmd/.*\.go]
        arguments: [10]

      - name: cyclomatic
        disabled: true

      - name: exported
        arguments: [checkPrivateReceivers, sayRepetitiveInsteadOfStutters]

      - name: function-length
        exclude: [TEST]

      - name: line-length-limit
        arguments: [120]

      - name: unhandled-error
        arguments: [fmt\..*]

      - name: unused-parameter
        arguments:
          # Ignore all parameters beginning with "_"
          - allowRegex: ^_

  testifylint:
    enable-all: true
