# ------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright © 2024 bomctl authors
# SPDX-FileName: .goreleaser.yml
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: bomctl

env:
  - CGO_ENABLED=0
  - COSIGN_YES=true
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

sboms:
  - id: generate-cyclonedx
    artifacts: archive
    documents: [$artifact.cdx.json]
    cmd: syft
    args: [scan, $artifact, --output, cyclonedx-json=$document]

  - id: generate-spdx
    artifacts: archive
    documents: [$artifact.spdx.json]
    cmd: syft
    args: [scan, $artifact, --output, spdx-json=$document]

gomod:
  mod: mod
  proxy: true

builds:
  - binary: "{{.ProjectName}}"
    mod_timestamp: "{{.CommitTimestamp}}"
    flags: [-trimpath]
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags: -s -w
      -X=github.com/bomctl/bomctl/cmd.VersionMajor={{.Major}}
      -X=github.com/bomctl/bomctl/cmd.VersionMinor={{.Minor}}
      -X=github.com/bomctl/bomctl/cmd.VersionPatch={{.Patch}}
      -X=github.com/bomctl/bomctl/cmd.VersionPre={{with .Prerelease}}-{{.}}{{end}}
      -X=github.com/bomctl/bomctl/cmd.BuildDate={{.Date}}

signs:
  - id: checksum-keyless-signing
    signature: "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    cmd: cosign
    args: [sign-blob, --output-signature=$signature, --output-certificate=$certificate, $artifact]
    artifacts: checksum

  - id: binary-keyless-signing
    signature: "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    cmd: cosign
    args: [sign-blob, --output-signature=$signature, --output-certificate=$certificate, $artifact]
    artifacts: binary

  - id: package-keyless-signing
    signature: "${artifact}-keyless.sig"
    certificate: "${artifact}-keyless.pem"
    cmd: cosign
    args: [sign-blob, --output-signature=$signature, --output-certificate=$certificate, $artifact]
    artifacts: package

nfpms:
  - license: Apache License 2.0
    maintainer: bomctl authors
    homepage: https://github.com/bomctl/bomctl
    description: Simpler Software Bill of Materials management
    formats: [apk, deb, rpm]

archives:
  - strip_binary_directory: true
    format_overrides:
      - goos: windows
        format: zip

snapshot:
  name_template: SNAPSHOT-{{.ShortCommit}}

changelog:
  disable: false
  use: github
  sort: asc
  abbrev: -1
  groups:
    - title: 🆕 New features
      regexp: ^.*?feat(\([[:word:]]+\))??!?:.+$
      order: 0

    - title: 🐞 Bug fixes
      regexp: ^.*?(bug|fix)(\([[:word:]]+\))??!?:.+$
      order: 1

    - title: 📘 Documentation
      regexp: ^.*?docs(\([[:word:]]+\))??!?:.+$
      order: 2

    - title: 📝 Other changes
      regexp: ^.*?(refactor|perf|test)(\([[:word:]]+\))??!?:.+$
      order: 999

  filters:
    include:
      - ^.*?(feat|bug|fix|docs|refactor|perf|test)(\([[:word:]]+\))??!?:.+$

release:
  prerelease: auto
  draft: true # allow for manual edits
  github:
    owner: bomctl
    name: bomctl
