# ------------------------------------------------------------------------
# SPDX-FileCopyrightText: Copyright © 2024 bomctl authors
# SPDX-FileName: .github/workflows/semantic-release.yml
# SPDX-FileType: SOURCE
# SPDX-License-Identifier: Apache-2.0
# ------------------------------------------------------------------------
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------
---
name: go-semantic-release
on:
  push:

  pull_request:
    branches:
      - main
      - next
      - dev
      - alpha
      - "[0-9.]*[0-9].x"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: "1.21"
          cache: false

      - uses: go-semantic-release/action@48d83acd958dae62e73701aad20a5b5844a3bf45 # v1.23.0
        with:
          changelog-file: docs/CHANGELOG.md
          changelog-generator-opt: emojis=true
          dry: ${{ !contains(fromJSON('["main", "next", "dev", "alpha"]'), github.ref_name) && !endsWith(github.ref, '.x') }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          hooks: goreleaser
          prepend: true
          prerelease: ${{ contains(fromJSON('["dev", "alpha"]'), github.ref_name) }}
